<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\aot\STFU.Animation\STFU.Animation.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Assets\STFU.Assets.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Common\STFU.Common.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Mesh\STFU.Mesh.csproj" />
    <ProjectReference Include="..\STFU.Import\STFU.Import.csproj" />
    <ProjectReference Include="..\STFU.Logging\STFU.Logging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeFbxDll>$(MSBuildThisFileDirectory)..\..\..\artifacts\native\STFU.Native.Fbx\stfu_fbx.dll</NativeFbxDll>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(NativeFbxDll)')">
    <None Include="$(NativeFbxDll)"
          Link="stfu_fbx.dll"
          TargetPath="stfu_fbx.dll"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
