<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\STFU.Abstractions\STFU.Abstractions.csproj" />
    <ProjectReference Include="..\STFU.Common\STFU.Common.csproj" />
    <ProjectReference Include="..\STFU.Messaging\STFU.Messaging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

</Project>
