<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\aot\STFU.Assets\STFU.Assets.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Camera\STFU.Camera.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Common\STFU.Common.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Engine\STFU.Engine.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Mesh\STFU.Mesh.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Messaging\STFU.Messaging.csproj" />
    <ProjectReference Include="..\..\aot\STFU.NPR\STFU.NPR.csproj" />
    <ProjectReference Include="..\..\aot\npr\pipelines\STFU.NPR.Pipelines.Abstractions\STFU.NPR.Pipelines.Abstractions.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Parallelism\STFU.Parallelism.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Rendering.Abstractions\STFU.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Strokes\STFU.Strokes.csproj" />
    <ProjectReference Include="..\..\aot\STFU.Viewport\STFU.Viewport.csproj" />
    <ProjectReference Include="..\STFU.Import\STFU.Import.csproj" />
    <ProjectReference Include="..\STFU.Import.Fbx\STFU.Import.Fbx.csproj" />
    <ProjectReference Include="..\STFU.Logging\STFU.Logging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
